// Declarative field schema per content type — drives the generic
// ResourceTable + ResourceForm so Events/Products/Blog/Sponsors/Testimonials/
// Challenges don't each need their own hand-built CRUD page.
//
// field.type: "text" | "textarea" | "number" | "boolean" | "tags" | "image" | "slug" | "map"

export const resources = {
  events: {
    table: "events",
    title: "Events",
    singular: "Event",
    orderBy: "sort_order",
    listColumns: ["title", "event_date", "published"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "URL Slug", type: "slug", from: "title", required: true, hint: "Auto-generated from the title — this becomes the event's web address, e.g. rideteagupshup.com/events/endurance-league-2. Only edit it if you know what you're doing." },
      { name: "event_date", label: "Date", type: "text", placeholder: "e.g. June 2027" },
      { name: "event_type", label: "Type", type: "text", placeholder: "e.g. Pan India Virtual Challenge" },
      { name: "categories", label: "Categories", type: "tags", placeholder: "Cycling, Running" },
      { name: "prize_pool", label: "Prize Pool (₹)", type: "number", placeholder: "e.g. 500000", hint: "Enter the amount in rupees only — it will be formatted as currency on the site automatically." },
      { name: "description", label: "Description", type: "textarea" },
      { name: "cover_image_url", label: "Cover Image", type: "image", folder: "events" },
      { name: "route_info", label: "Route Description", type: "textarea", placeholder: "Start/finish, key waypoints..." },
      { name: "route_map_query", label: "Route Map", type: "map", placeholder: "e.g. Nehru Park, New Delhi", hint: "Type a place, address, or route name — we'll show a live map preview and embed it on the event page." },
      { name: "elevation_gain", label: "Elevation Gain", type: "text", placeholder: "e.g. 1,200m" },
      { name: "gpx_url", label: "GPX File Link", type: "text", placeholder: "https://..." },
      { name: "results_summary", label: "Results", type: "textarea", placeholder: "Link or summary of results" },
      { name: "previous_edition_summary", label: "Previous Edition", type: "textarea" },
      { name: "featured", label: "Featured on homepage", type: "boolean", default: false },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  products: {
    table: "products",
    title: "Merchandise",
    singular: "Product",
    orderBy: "sort_order",
    listColumns: ["name", "price", "in_stock"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "price", label: "Price (₹)", type: "number", required: true },
      { name: "tag", label: "Tag", type: "text", placeholder: "e.g. Bestseller" },
      { name: "image_url", label: "Product Photo", type: "image", folder: "products" },
      { name: "in_stock", label: "In Stock", type: "boolean", default: true },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
    ],
  },
  blog: {
    table: "blog_posts",
    title: "Blog",
    singular: "Post",
    orderBy: "published_at",
    ascending: false,
    listColumns: ["title", "category", "published"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug (used in the URL)", type: "text", required: true },
      { name: "category", label: "Category", type: "text", placeholder: "e.g. Cycling Tips" },
      { name: "excerpt", label: "Excerpt", type: "textarea" },
      { name: "content", label: "Full Content", type: "textarea" },
      { name: "cover_image_url", label: "Cover Image", type: "image", folder: "blog" },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  sponsors: {
    table: "sponsors",
    title: "Sponsors",
    singular: "Sponsor",
    orderBy: "sort_order",
    listColumns: ["name", "tier"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "logo_url", label: "Logo", type: "image", folder: "sponsors" },
      { name: "tier", label: "Tier", type: "text", placeholder: "e.g. Title Sponsor" },
      { name: "website_url", label: "Website", type: "text", placeholder: "https://" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
    ],
  },
  testimonials: {
    table: "testimonials",
    title: "Testimonials",
    singular: "Testimonial",
    orderBy: "sort_order",
    listColumns: ["name", "role", "published"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "role", label: "Role", type: "text", placeholder: "e.g. Runner, Delhi" },
      { name: "quote", label: "Quote", type: "textarea", required: true },
      { name: "avatar_url", label: "Photo", type: "image", folder: "testimonials" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  challenges: {
    table: "challenges",
    title: "Challenges",
    singular: "Challenge",
    orderBy: "sort_order",
    listColumns: ["title", "period"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "period", label: "Period", type: "text", placeholder: "e.g. Jan – Mar 2027" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
    ],
  },
  team: {
    table: "team_members",
    title: "Team",
    singular: "Team Member",
    orderBy: "sort_order",
    listColumns: ["name", "role", "city", "published"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "role", label: "Role", type: "text", placeholder: "e.g. Founder & Head Coach" },
      { name: "city", label: "City", type: "text" },
      { name: "sport", label: "Sport", type: "text", placeholder: "e.g. Cycling & Triathlon" },
      { name: "instagram_url", label: "Instagram", type: "text", placeholder: "https://instagram.com/..." },
      { name: "avatar_url", label: "Photo", type: "image", folder: "team" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  raceResults: {
    table: "race_results",
    title: "Race Results",
    singular: "Result",
    orderBy: "year",
    ascending: false,
    listColumns: ["event_name", "athlete_name", "position", "year"],
    fields: [
      { name: "event_name", label: "Event Name", type: "text", required: true },
      { name: "athlete_name", label: "Athlete Name", type: "text", required: true },
      { name: "category", label: "Category", type: "text", placeholder: "e.g. Cycling — Open" },
      { name: "finish_time", label: "Finish Time", type: "text", placeholder: "e.g. 4:12:08" },
      { name: "position", label: "Position", type: "text", placeholder: "e.g. 1st, Finisher" },
      { name: "year", label: "Year", type: "text", placeholder: "e.g. 2027" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
    ],
  },
};
