// Declarative field schema per content type — drives the generic
// ResourceTable + ResourceForm so Events/Products/Blog/Sponsors/Testimonials/
// Challenges don't each need their own hand-built CRUD page.
//
// field.type: "text" | "textarea" | "number" | "boolean" | "tags" | "image" | "slug" | "map" | "date" | "select" | "color" | "relation"
//
// "relation" is a dropdown filled from another table's rows:
//   { type: "relation", table, valueColumn, labelColumn }
// A "number" field takes whole numbers unless it has step: "any"; with
// optional: true a blank box is saved as "no value" instead of 0.
// field.showWhen = { field, in: [...] } shows the field only while another
// field of the same form holds one of those values.

// Keys of the line-art icons drawn by components/sections/WhyRtg.jsx
// (WHY_ICONS) — keep the two in step.
const WHY_ICON_OPTIONS = [
  { value: "training", label: "Bike + rider (training)" },
  { value: "community", label: "Group of people (community)" },
  { value: "running", label: "Runner" },
  { value: "cycling", label: "Bike with flag (cycling skills)" },
  { value: "consistency", label: "Clock (consistency)" },
  { value: "recognition", label: "Star medal (recognition)" },
  { value: "adventure", label: "Mountains + flag (adventure)" },
  { value: "memories", label: "Route with pins (memories)" },
];

export const resources = {
  events: {
    table: "events",
    title: "Events",
    singular: "Event",
    orderBy: "sort_order",
    listColumns: ["title", "event_status", "event_date", "published"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "URL Slug", type: "slug", from: "title", required: true, hint: "Auto-generated from the title — this becomes the event's web address, e.g. rideteagupshup.com/events/endurance-league-2. Only edit it if you know what you're doing." },
      {
        name: "event_status",
        label: "Category on Events Page",
        type: "select",
        options: ["Flagship", "Community", "Virtual", "Past"],
        default: "Community",
        hint: "The filter this event sits under on the Events page. \"Past\" also keeps it out of the homepage's Upcoming Events.",
      },
      { name: "event_date", label: "Date / Status", type: "text", placeholder: "e.g. June 2027, Coming Soon, Saturdays", hint: "Free text. Shown as the event's status line on the Events page and as a pill on the homepage." },
      {
        name: "tone",
        label: "Colour on Events Page",
        type: "select",
        options: [
          { value: "sunset", label: "Sunset (coral → pink)" },
          { value: "electric", label: "Electric (cyan → blue)" },
          { value: "trail", label: "Trail (lime → teal)" },
          { value: "blue", label: "Blue (cyan → indigo)" },
          { value: "warm", label: "Warm (red → yellow)" },
          { value: "mint", label: "Mint (green → teal)" },
          { value: "future", label: "Future (violet → pink)" },
        ],
        hint: "Optional. The accent colours of this event's cards on the Events page. If not set, colours rotate automatically.",
      },
      { name: "event_type", label: "Type", type: "text", placeholder: "e.g. Flagship MTB Race", hint: "The small coloured line on the event's card (Events page) and the tag on its homepage slide." },
      { name: "categories", label: "Categories", type: "tags", placeholder: "Cycling, Running" },
      { name: "prize_pool", label: "Prize Pool (₹)", type: "number", placeholder: "e.g. 500000", hint: "Enter the amount in rupees only — it will be formatted as currency on the site automatically." },
      { name: "description", label: "Description", type: "textarea" },
      { name: "cover_image_url", label: "Cover Image", type: "image", folder: "events" },
      { name: "route_info", label: "Route Description", type: "textarea", placeholder: "Start/finish, key waypoints..." },
      { name: "route_map_query", label: "Route Map", type: "map", placeholder: "e.g. Nehru Park, New Delhi", hint: "Type a place, address, or route name — we'll show a live map preview and embed it on the event page." },
      { name: "elevation_gain", label: "Elevation Gain", type: "text", placeholder: "e.g. 1,200m" },
      { name: "gpx_url", label: "GPX File Link", type: "text", placeholder: "https://..." },
      { name: "results_summary", label: "Results", type: "textarea", placeholder: "Link or summary of results" },
      { name: "previous_edition_summary", label: "Previous Edition", type: "textarea" },
      {
        name: "featured",
        label: "Featured on homepage",
        type: "boolean",
        default: false,
        hint: "Separate from the Events page section above — check this to pick exactly which events appear as large slides in the homepage's Upcoming Events. If no event is checked, every Signature and Coming Up event is shown there. The slide uses the Type as its tag, plus the optional fields below.",
      },
      { name: "home_title_accent", label: "Homepage slide — colored part of the title", type: "text", placeholder: "e.g. Challenge 2026", hint: "Optional. Must be the end of the Title exactly. If empty, the second half of the title is colored." },
      { name: "home_pills", label: "Homepage slide — pills", type: "text", placeholder: "Nov / Dec 2026, 30–50 KM, Race Categories + Awards", hint: "Optional, comma-separated. If empty, the Date and Categories are used." },
      { name: "highlight_label", label: "Homepage slide — side card label", type: "text", placeholder: "e.g. Highlights" },
      { name: "highlight_title", label: "Homepage slide — side card heading", type: "text", placeholder: "e.g. Overall • Pro • Age Categories" },
      { name: "highlight_text", label: "Homepage slide — side card text", type: "textarea", hint: "The side card is hidden when its heading and text are both empty." },
      { name: "secondary_button_label", label: "Homepage slide — second button label", type: "text", placeholder: "e.g. Register Interest", hint: "Optional. The default label and link are set in Site Content → Home." },
      { name: "secondary_button_link", label: "Homepage slide — second button link", type: "text", placeholder: "e.g. /contact" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  products: {
    table: "products",
    title: "Merchandise",
    singular: "Product",
    orderBy: "sort_order",
    listColumns: ["name", "price", "in_stock"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "price", label: "Price (₹)", type: "number", required: true },
      { name: "tag", label: "Tag", type: "text", placeholder: "e.g. Bestseller", hint: "Shown as a pill on the product photo." },
      { name: "eyebrow", label: "Small line above the name", type: "text", placeholder: "e.g. Performance", hint: "Optional. Shown on the homepage's Merchandise Highlights cards." },
      { name: "description", label: "Description", type: "textarea", hint: "Shown on the product's own page, and (first two lines) on the homepage's Merchandise Highlights cards." },
      { name: "sizes", label: "Sizes", type: "tags", placeholder: "S, M, L, XL", hint: "Leave blank for products that don't come in sizes (cap, bottle, etc.). If set, buyers must pick one before adding to cart." },
      { name: "image_url", label: "Product Photo", type: "image", folder: "products" },
      { name: "in_stock", label: "In Stock", type: "boolean", default: true },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
    ],
  },
  blog: {
    table: "blog_posts",
    title: "Blog",
    singular: "Post",
    orderBy: "published_at",
    ascending: false,
    listColumns: ["title", "category", "published"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug (used in the URL)", type: "text", required: true },
      { name: "category", label: "Category", type: "text", placeholder: "e.g. Cycling Tips" },
      { name: "excerpt", label: "Excerpt", type: "textarea" },
      { name: "content", label: "Full Content", type: "textarea" },
      { name: "cover_image_url", label: "Cover Image", type: "image", folder: "blog" },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  sponsors: {
    table: "sponsors",
    title: "Sponsors",
    singular: "Sponsor",
    orderBy: "sort_order",
    listColumns: ["name", "tier"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "logo_url", label: "Logo", type: "image", folder: "sponsors" },
      { name: "tier", label: "Tier", type: "text", placeholder: "e.g. Title Sponsor" },
      { name: "website_url", label: "Website", type: "text", placeholder: "https://" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
    ],
  },
  testimonials: {
    table: "testimonials",
    title: "Testimonials",
    singular: "Testimonial",
    orderBy: "sort_order",
    listColumns: ["name", "role", "published"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "role", label: "Role", type: "text", placeholder: "e.g. Runner, Delhi" },
      { name: "quote", label: "Quote", type: "textarea", required: true },
      { name: "avatar_url", label: "Photo", type: "image", folder: "testimonials" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  challenges: {
    table: "challenges",
    title: "Challenges",
    singular: "Challenge",
    orderBy: "sort_order",
    listColumns: ["title", "period"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "period", label: "Period", type: "text", placeholder: "e.g. Jan – Mar 2027" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
    ],
  },
  team: {
    table: "team_members",
    title: "Team",
    singular: "Team Member",
    orderBy: "sort_order",
    listColumns: ["name", "role", "city", "published"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "role", label: "Role", type: "text", placeholder: "e.g. Founder & Head Coach" },
      { name: "city", label: "City", type: "text" },
      { name: "sport", label: "Sport", type: "text", placeholder: "e.g. Cycling & Triathlon" },
      { name: "instagram_url", label: "Instagram", type: "text", placeholder: "https://instagram.com/..." },
      { name: "avatar_url", label: "Photo", type: "image", folder: "team" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  raceResults: {
    table: "race_results",
    title: "Race Results",
    singular: "Result",
    orderBy: "year",
    ascending: false,
    listColumns: ["event_name", "athlete_name", "position", "year"],
    fields: [
      { name: "event_name", label: "Event Name", type: "text", required: true },
      { name: "athlete_name", label: "Athlete Name", type: "text", required: true },
      { name: "category", label: "Category", type: "text", placeholder: "e.g. Cycling — Open" },
      { name: "finish_time", label: "Finish Time", type: "text", placeholder: "e.g. 4:12:08" },
      { name: "position", label: "Position", type: "text", placeholder: "e.g. 1st, Finisher" },
      { name: "year", label: "Year", type: "text", placeholder: "e.g. 2027" },
      { name: "certificate_url", label: "Finisher Certificate", type: "image", folder: "certificates", hint: "Optional — upload a certificate image and a \"Download Certificate\" button appears for this result." },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
    ],
  },
  leaderboardEntries: {
    table: "leaderboard_entries",
    title: "Leaderboard — Athletes",
    singular: "Athlete",
    orderBy: "sort_order",
    listColumns: ["athlete_name", "challenge_slug", "sport_slug", "points", "published"],
    fields: [
      { name: "athlete_name", label: "Athlete Name", type: "text", required: true, placeholder: "e.g. Aarav Mehta" },
      { name: "city", label: "City", type: "text", placeholder: "e.g. Delhi NCR", hint: "Shown under the name in the ranking table." },
      { name: "challenge_slug", label: "Event / Challenge", type: "relation", table: "leaderboard_challenges", valueColumn: "slug", labelColumn: "name", required: true, hint: "The board this row belongs to. An athlete in two challenges gets one row per challenge. Add challenges in Leaderboard — Challenges." },
      { name: "sport_slug", label: "Sport", type: "relation", table: "leaderboard_sports", valueColumn: "slug", labelColumn: "name", hint: "Add or rename sports in Leaderboard — Sports." },
      { name: "gender", label: "Gender", type: "select", options: ["Male", "Female", "Other"] },
      { name: "age_group_slug", label: "Age Group", type: "relation", table: "leaderboard_age_groups", valueColumn: "slug", labelColumn: "name", hint: "Add or rename brackets in Leaderboard — Age Groups." },
      { name: "sessions", label: "Sessions", type: "number", default: 0, hint: "How many sessions they completed." },
      { name: "distance_km", label: "Distance (km)", type: "number", step: "any", default: 0 },
      { name: "consistency", label: "Consistency (%)", type: "number", default: 0, hint: "A whole number from 0 to 100." },
      { name: "points", label: "Points", type: "number", default: 0, hint: "The page ranks athletes by points unless the visitor picks something else." },
      { name: "trend", label: "Checkpoint Scores", type: "text", placeholder: "e.g. 66, 72, 79, 86, 92, 100", hint: "Optional. Their score at each checkpoint, oldest first, separated by commas. Draws their trend line and the Momentum chart." },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0, hint: "Only the order of this admin list — the page ranks athletes by their numbers." },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  leaderboardChallenges: {
    table: "leaderboard_challenges",
    title: "Leaderboard — Challenges",
    singular: "Challenge",
    orderBy: "sort_order",
    listColumns: ["name", "slug", "sort_order", "published"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, placeholder: "e.g. Endurance League Vol. 2", hint: "Each one is a choice in the Leaderboard page's Event / Challenge dropdown." },
      { name: "slug", label: "Short Code", type: "slug", from: "name", required: true, hint: "Auto-generated from the name. Athletes are filed under this code — leave it as it is." },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0, hint: "Order in the dropdown." },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  leaderboardSports: {
    table: "leaderboard_sports",
    title: "Leaderboard — Sports",
    singular: "Sport",
    orderBy: "sort_order",
    listColumns: ["name", "filter_label", "color", "sort_order", "published"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, placeholder: "e.g. Cycling", hint: "Each sport is a filter pill and a slice of the Sport Mix ring." },
      { name: "slug", label: "Short Code", type: "slug", from: "name", required: true, hint: "Auto-generated from the name. Athletes are filed under this code — leave it as it is." },
      { name: "filter_label", label: "Wording on the Filter Pill", type: "text", placeholder: "e.g. Mixed / Events", hint: "Optional. If empty, the name is used." },
      { name: "color", label: "Colour", type: "color", default: "#6568ff", hint: "The colour of this sport's slice of the Sport Mix ring." },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0, hint: "Order of the filter pills, left to right." },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  leaderboardAgeGroups: {
    table: "leaderboard_age_groups",
    title: "Leaderboard — Age Groups",
    singular: "Age Group",
    orderBy: "sort_order",
    listColumns: ["name", "filter_label", "sort_order", "published"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, placeholder: "e.g. Under 25", hint: "Each bracket is a filter pill and a bar of the Age Distribution card." },
      { name: "slug", label: "Short Code", type: "slug", from: "name", required: true, hint: "Auto-generated from the name. Athletes are filed under this code — leave it as it is." },
      { name: "filter_label", label: "Wording on the Filter Pill", type: "text", placeholder: "e.g. U25", hint: "Optional. If empty, the name is used." },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0, hint: "Youngest first." },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  ridgeResults: {
    table: "ridge_results",
    title: "Ridge Repeats — Results",
    singular: "Result",
    orderBy: "sort_order",
    listColumns: ["athlete_name", "session_slug", "loop_times", "score", "published"],
    fields: [
      { name: "athlete_name", label: "Rider Name", type: "text", required: true, placeholder: "e.g. Athlete R01" },
      { name: "session_slug", label: "Session", type: "relation", table: "ridge_sessions", valueColumn: "slug", labelColumn: "name", required: true, hint: "Add sessions in Ridge Repeats — Sessions." },
      { name: "loop_times", label: "Loop Times", type: "text", placeholder: "e.g. 21:16, 20:58, 20:29, 20:04, 19:42", hint: "Each loop as minutes:seconds, in order, separated by commas. Average loop, improvement and completion are worked out from these." },
      { name: "score", label: "Score", type: "number", step: "any", default: 0, placeholder: "e.g. 34.6", hint: "Riders are ranked by score, highest first." },
      { name: "improvement_pct", label: "Improvement % (optional)", type: "number", step: "any", optional: true, placeholder: "e.g. 8.42", hint: "Leave empty to work it out from the first and last loop time." },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0, hint: "Only the order of this admin list." },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  ridgeSessions: {
    table: "ridge_sessions",
    title: "Ridge Repeats — Sessions",
    singular: "Session",
    orderBy: "sort_order",
    listColumns: ["name", "loop_count", "sort_order", "published"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, placeholder: "e.g. Saturday 12 October", hint: "Each one is a choice in the Ridge Repeats \"Session\" dropdown. The first one is shown when the page opens." },
      { name: "slug", label: "Short Code", type: "slug", from: "name", required: true, hint: "Auto-generated from the name. Results are filed under this code — leave it as it is." },
      { name: "loop_count", label: "Loops in the Session", type: "number", default: 5, hint: "A rider's completion % is their recorded loops out of this." },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0, hint: "Order in the dropdown." },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  calendarCategories: {
    table: "calendar_categories",
    title: "Calendar — Activity Types",
    singular: "Activity Type",
    orderBy: "sort_order",
    listColumns: ["name", "detail_label", "color", "sort_order", "published"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, placeholder: "e.g. Brick", hint: "Each activity type is a filter pill above the calendar, a pill under the Weekly Rhythm panel and a floating tag in the page's hero (the first three)." },
      { name: "slug", label: "Short Code", type: "slug", from: "name", required: true, hint: "Auto-generated from the name. Activities are filed under this code — leave it as it is." },
      { name: "detail_label", label: "Name in the Detail Window", type: "text", placeholder: "e.g. Brick Session", hint: "Optional. Shown at the top of an activity's detail window. If empty, the name is used." },
      { name: "color", label: "Colour", type: "color", default: "#35246f", hint: "The colour of this type's activities everywhere on the Calendar page." },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0, hint: "Order of the filter pills, left to right." },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  calendarActivities: {
    table: "calendar_activities",
    title: "Calendar — Activities",
    singular: "Activity",
    orderBy: "sort_order",
    listColumns: ["title", "schedule_type", "weekday", "activity_date", "category_slug", "published"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true, placeholder: "e.g. RTG Brick & Burn" },
      { name: "category_slug", label: "Activity Type", type: "relation", table: "calendar_categories", valueColumn: "slug", labelColumn: "name", hint: "Decides its colour and which filter it sits under. Add or rename types in Calendar — Activity Types." },
      {
        name: "schedule_type",
        label: "When does it happen?",
        type: "select",
        required: true,
        default: "weekly",
        options: [
          { value: "weekly", label: "Every week, on the same day" },
          { value: "once", label: "Once, on one date" },
          { value: "flexible", label: "No fixed day yet" },
        ],
        hint: "\"Every week\" puts it on that weekday of every month. \"Once\" puts it on one date. \"No fixed day yet\" keeps it off the day grid — it is only listed in the Weekly Rhythm panel.",
      },
      { name: "weekday", label: "Day of the Week", type: "select", options: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"], required: true, showWhen: { field: "schedule_type", in: ["weekly"] } },
      { name: "activity_date", label: "Date", type: "date", required: true, showWhen: { field: "schedule_type", in: ["once"] } },
      { name: "when_text", label: "Shown Instead of a Day", type: "text", placeholder: "e.g. Weekend", showWhen: { field: "schedule_type", in: ["flexible"] } },
      { name: "time_text", label: "Time", type: "text", placeholder: "e.g. 5:00 – 6:30 AM", hint: "Optional. If it starts with a clock time (5:00 AM), \"Add to Calendar\" saves it at that time; otherwise as an all-day entry." },
      { name: "city", label: "City / Region", type: "text", placeholder: "e.g. Delhi NCR" },
      { name: "location", label: "Location", type: "text", placeholder: "e.g. Nehru Park" },
      { name: "format", label: "Format", type: "text", placeholder: "e.g. Ride + Run + Mobility" },
      { name: "summary", label: "Summary", type: "textarea", placeholder: "One or two sentences about the activity.", hint: "The paragraph in its detail window." },
      { name: "organiser", label: "Hosted By", type: "text", placeholder: "e.g. RTG Delhi", hint: "Optional — the group or community running it." },
      { name: "status_label", label: "Status", type: "text", placeholder: "e.g. Recurring Community Session, Registration Open" },
      { name: "note", label: "Note", type: "textarea", placeholder: "e.g. Helmet mandatory. Reporting 15 minutes before the start.", hint: "Optional. Shown in a highlighted box at the bottom of the detail window." },
      { name: "link_url", label: "Button Link", type: "text", placeholder: "e.g. /events/rtg-mtb-challenge-2026", hint: "Optional. Adds a button to the detail window — a page on this site (starts with /) or a full web address (https://…)." },
      { name: "link_label", label: "Button Label", type: "text", placeholder: "e.g. Register", hint: "Optional. The default label is set in Site Content → Calendar." },
      { name: "show_in_rhythm", label: "Also list in the \"Weekly Rhythm\" panel", type: "boolean", default: false },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0, hint: "Order within a day, and in the Weekly Rhythm panel." },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  weeklySessions: {
    table: "weekly_sessions",
    title: "Weekly Sessions",
    singular: "Session",
    orderBy: "sort_order",
    listColumns: ["day", "name", "difficulty", "published"],
    fields: [
      { name: "day", label: "Day", type: "select", options: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"], required: true },
      { name: "name", label: "Session Name", type: "text", required: true, placeholder: "e.g. Friday Bricks" },
      { name: "slug", label: "URL Slug", type: "slug", from: "name", required: true, hint: "Auto-generated from the session name — this becomes its own page address, e.g. rideteagupshup.com/weekly-rides/friday-bricks." },
      { name: "time", label: "Time", type: "text", placeholder: "e.g. 5:00 – 6:30 AM" },
      { name: "location", label: "Location", type: "text", placeholder: "e.g. Nehru Park, Delhi" },
      { name: "route_map_query", label: "Route Map", type: "map", placeholder: "e.g. Nehru Park, New Delhi" },
      { name: "format", label: "Format", type: "text", placeholder: "e.g. 30km Cycling + 5km Run" },
      { name: "difficulty", label: "Difficulty", type: "select", options: ["Beginner", "Intermediate", "Advanced", "All Levels"] },
      { name: "pace_group", label: "Pace Group", type: "text", placeholder: "e.g. A (fast) / B (moderate) / C (social)" },
      { name: "cost", label: "Cost", type: "text", placeholder: "e.g. Free" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  faqs: {
    table: "faqs",
    title: "FAQ",
    singular: "Question",
    orderBy: "sort_order",
    listColumns: ["question", "published"],
    fields: [
      { name: "question", label: "Question", type: "text", required: true },
      { name: "answer", label: "Answer", type: "textarea", required: true },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  rideFaqs: {
    table: "ride_faqs",
    title: "Ride FAQs",
    singular: "Question",
    orderBy: "sort_order",
    listColumns: ["question", "published"],
    fields: [
      { name: "question", label: "Question", type: "text", required: true, hint: "Shown on the Weekly Rides page's FAQ section." },
      { name: "answer", label: "Answer", type: "textarea", required: true },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  rideSafety: {
    table: "ride_safety",
    title: "Ride Safety Checklist",
    singular: "Checklist Item",
    orderBy: "sort_order",
    listColumns: ["item", "published"],
    fields: [
      { name: "item", label: "Checklist Item", type: "text", required: true, hint: "Shown on Weekly Rides and the Safety page's \"Weekly Session Checklist\"." },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  whatToBring: {
    table: "what_to_bring",
    title: "What to Bring",
    singular: "Item",
    orderBy: "sort_order",
    listColumns: ["item", "published"],
    fields: [
      { name: "item", label: "Item", type: "text", required: true, hint: "Shown on Weekly Rides and on an event's \"What to Bring\" preview." },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  generalSafety: {
    table: "general_safety",
    title: "General Safety",
    singular: "Guideline",
    orderBy: "sort_order",
    listColumns: ["title", "published"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true, placeholder: "e.g. Helmets, always" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  footerLinks: {
    table: "footer_links",
    title: "Footer Links",
    singular: "Link",
    orderBy: "column_order",
    listColumns: ["column_title", "label", "link_url", "sort_order", "published"],
    fields: [
      { name: "column_title", label: "Column Heading", type: "text", required: true, placeholder: "e.g. Community", hint: "Links with exactly the same heading form one footer column. Type a new heading to start a new column." },
      { name: "column_order", label: "Column Position", type: "number", default: 1, hint: "1 = first column on the left. Use the same number on every link in a column." },
      { name: "label", label: "Link Text", type: "text", required: true, placeholder: "e.g. Weekly Rides" },
      { name: "link_url", label: "Link", type: "text", required: true, placeholder: "e.g. /weekly-rides", hint: "A page on this site (starts with /) or a full web address (https://…)." },
      { name: "sort_order", label: "Position in Column", type: "number", default: 0, hint: "Top to bottom." },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  homeWhyReasons: {
    table: "home_why_reasons",
    title: "Home — Why RTG Cards",
    singular: "Card",
    orderBy: "sort_order",
    listColumns: ["title", "pill", "sort_order", "published"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true, placeholder: "e.g. Train Together", hint: "Shown on Home's \"Why RTG\" section, in the scrolling card stack. The section's own heading and button are in Site Content → Home." },
      { name: "pill", label: "Small label above the title", type: "text", placeholder: "e.g. Weekly Training" },
      { name: "description", label: "Description", type: "textarea", placeholder: "One short sentence." },
      { name: "icon", label: "Icon", type: "select", options: WHY_ICON_OPTIONS, default: "training" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0, hint: "Cards are numbered 01, 02, 03… in this order." },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  homeTrainingFormats: {
    table: "home_training_formats",
    title: "Home — Training Formats",
    singular: "Format",
    orderBy: "sort_order",
    listColumns: ["tab_label", "title_line1", "sort_order", "published"],
    fields: [
      { name: "tab_label", label: "Tab Name", type: "text", required: true, placeholder: "e.g. Ridge Repeats", hint: "Each format is one tab of Home's dark \"Training Formats\" band. In any text below, wrap words in *stars* to draw them in orange, e.g. Led by *Manish Jayal*." },
      { name: "kicker", label: "Small line above the headline", type: "text", placeholder: "e.g. RTG Ridge Repeats • Led by *Manish Jayal*" },
      { name: "title_line1", label: "Headline — line 1 (outlined)", type: "text", required: true, placeholder: "e.g. RTG Ridge" },
      { name: "title_line2", label: "Headline — line 2 (filled)", type: "text", placeholder: "e.g. Repeats." },
      { name: "tagline", label: "Tagline", type: "text", placeholder: "You | vs | You", hint: "Three parts separated by | — the middle one is drawn smaller." },
      { name: "description", label: "Paragraph", type: "textarea" },
      { name: "pills", label: "Pills under the paragraph", type: "text", placeholder: "Delhi NCR, Saturday Mornings, Endurance Focus", hint: "Comma-separated." },
      { name: "note", label: "Highlighted note", type: "text", placeholder: "e.g. Exclusively under the RTG Membership Program" },
      { name: "button_label", label: "Button Label", type: "text", placeholder: "e.g. Explore Now" },
      { name: "link_url", label: "Button Link", type: "text", placeholder: "e.g. /weekly-rides" },
      { name: "image_url", label: "Background Photo", type: "image", folder: "home-training", hint: "Fills the whole band while this tab is active." },
      { name: "card_label", label: "Left card — small label", type: "text", placeholder: "e.g. Ridge Loop" },
      { name: "card_title", label: "Left card — title", type: "text", placeholder: "e.g. Talkatora Circuit" },
      { name: "card_image_url", label: "Left card — route map / picture", type: "image", folder: "home-training", hint: "Optional. Leave empty to show the numbered steps below instead." },
      { name: "card_stats", label: "Left card — pills under the picture", type: "text", placeholder: "5 Loops, 9.15 KM Each, ~45 KM Total", hint: "Comma-separated. Only shown with a picture." },
      { name: "card_steps", label: "Left card — numbered steps", type: "textarea", placeholder: "Ride | 60 Min\nTransition | Bike → Run\nRun | 30 Min", hint: "One per line as \"Label | Value\". Only shown when there's no picture." },
      { name: "card_meta", label: "Left card — detail boxes", type: "textarea", placeholder: "Start | Talkatora Stadium\nWhen | Saturday • 5:00 AM", hint: "One per line as \"Label | Value\". Four fit best." },
      { name: "panel_rows", label: "Right panel — rows", type: "textarea", placeholder: "Format | 5 × 9.15 KM Loops\nPoint System | Improvement % • PR Points", hint: "One per line as \"Label | Value\". Four fit best." },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0, hint: "Tab order, left to right." },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  homeWays: {
    table: "home_ways",
    title: "Home — Ways to Move Cards",
    singular: "Card",
    orderBy: "sort_order",
    listColumns: ["title", "kicker", "sort_order", "published"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true, placeholder: "e.g. Running", hint: "Shown on Home's \"More Ways to Move Together\" section, one card at a time. The section's own heading and paragraphs are in Site Content → Home." },
      { name: "kicker", label: "Small line above the title", type: "text", placeholder: "e.g. Run with RTG" },
      { name: "description", label: "Description", type: "textarea", placeholder: "e.g. Community runs, training, challenges." },
      { name: "image_url", label: "Photo", type: "image", folder: "home-ways" },
      { name: "link_url", label: "Link", type: "text", placeholder: "e.g. /weekly-rides", hint: "The page on this site the card opens when clicked." },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  sponsorTiers: {
    table: "sponsor_tiers",
    title: "Sponsor Tiers",
    singular: "Tier",
    orderBy: "sort_order",
    listColumns: ["name", "price", "published"],
    fields: [
      { name: "name", label: "Tier Name", type: "text", required: true, placeholder: "e.g. Title Sponsor" },
      { name: "price", label: "Price", type: "text", placeholder: "e.g. ₹5,00,000/year" },
      { name: "perks", label: "Perks", type: "tags", placeholder: "Logo on jerseys, Event naming rights, ..." },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  sponsorOpportunities: {
    table: "sponsor_opportunities",
    title: "Sponsorship Opportunities",
    singular: "Opportunity",
    orderBy: "sort_order",
    listColumns: ["title", "published"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true, placeholder: "e.g. Events" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  sizeGuide: {
    table: "size_guide",
    title: "Size Guide",
    singular: "Size Row",
    orderBy: "sort_order",
    listColumns: ["size", "chest", "length", "published"],
    fields: [
      { name: "size", label: "Size", type: "text", required: true, placeholder: "e.g. M" },
      { name: "chest", label: "Chest", type: "text", placeholder: "e.g. 39–41 in" },
      { name: "length", label: "Length", type: "text", placeholder: "e.g. 28 in" },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
  merchReviews: {
    table: "merch_reviews",
    title: "Merch Reviews",
    singular: "Review",
    orderBy: "sort_order",
    listColumns: ["name", "product", "rating", "published"],
    fields: [
      { name: "name", label: "Reviewer Name", type: "text", required: true, placeholder: "e.g. Ananya S." },
      { name: "product", label: "Product", type: "text", placeholder: "e.g. RTG Jersey" },
      { name: "rating", label: "Rating (1–5)", type: "number", default: 5 },
      { name: "quote", label: "Quote", type: "textarea", required: true },
      { name: "sort_order", label: "Sort Order", type: "number", default: 0 },
      { name: "published", label: "Published", type: "boolean", default: true },
    ],
  },
};
